language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-20.0.0
    - andorid-19
    - android-20
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-20

notifications:
  email: false

env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - ./scripts/wait_for_emulator.sh
  - adb shell input keyevent 82 &
